name: Cargo Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - name: Checkout Repository
        id: checkout_repository
        uses: stx-labs/actions/checkout@ed353a33594a2fa97ea6702d838e4a935cce374d

      - name: Setup Rust
        id: setup_rust
        uses: stx-labs/actions/setup-rust-toolchain@ed353a33594a2fa97ea6702d838e4a935cce374d

      - name: Cargo Publish
        id: cargo_publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
